minimal_mistakes_skin: dark
locale: ko-KR
title: Paseul's Devlog
title_separator: '-'
subtitle: null
name: Jaehoon Lee
description: 'C#, Python, Docker, Kubernetes, Deep learning, Reinforcement learning'
url: 'https://paseul.github.io/network/'
baseurl: null
repository: null
teaser: null
logo: null
masthead_title: null
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: paseul
staticman:
  allowedFields: null
  branch: null
  commitMessage: null
  filename: null
  format: null
  moderation: null
  path: null
  requiredFields: null
  transforms:
    email: null
  generatedFields:
    date:
      type: null
      options:
        format: null
  endpoint: null
reCaptcha:
  siteKey: null
  secret: null
atom_feed:
  path: null
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: 0ESNAQDTWC
  index_name: devlog
  search_only_api_key: 851e21fa985fedd9107836d9656afee6
  powered_by: null
google:
  search_engine_id: null
  instant_search: null
google_site_verification: null
bing_site_verification: null
yandex_site_verification: null
naver_site_verification: null
og_image: /assets/images/page-header-og-image.png
social:
  type: null
  name: null
  links: null
google_analytics: UA-152547676-1
author:
  name: Jaehoon Lee
  avatar: assets/images/bio-photo-2.jpg
  bio: I am an **amazing** person.
  location: KOREA
  email: machianb@naver.com
  github: paseul
  linkedin: jaehoon265779188
  links:
    - label: Email
      icon: fas fa-fw fa-envelope-square
    - label: Website
      icon: fas fa-fw fa-link
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
    - label: GitHub
      icon: fab fa-fw fa-github
footer:
  links:
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/jaehoon265779188/"
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/paseul"
include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: utf-8
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: |+
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: '/:categories/:title/'
paginate: 5
paginate_path: '/page:num/'
timezone: null
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: false
      related: true
  - scope:
      path: _pages
      type: splash
    values:
      layout: single
      author_profile: true
